[package]
name = "bk7084-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "bk7084"
crate-type = ["cdylib"]

[package.metadata.maturin]
name = "bk7084.bk7084rs"

[dependencies]
cfg-if = "1"
env_logger = "0.9"
log = "0.4"
pyo3 = { version = "0.17.1", features = ["extension-module"] }
winit = "0.27"
wgpu = "0.13"
